workflow:
  steps:
    - name: "Responsable Produit"
      description: "Gère la vision d'un produit et veille à ce que l'équipe le développe selon les besoins des utilisateurs."
      model: "llama3.2:1b"
      personaFile: "resources/product-owner-persona.md"
      sentences:
        - text: "Génère un document en Markdown qui décrit l'architecture du système en tenant compte des besoins utilisateurs suivants : [insérer besoins]."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
        
        - text: "Rédige un document en Markdown détaillant l'approche technique pour répondre aux exigences de performance et de scalabilité suivantes : [insérer exigences]."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
        
        - text: "Crée un diagramme UML dans un fichier Markdown qui illustre l'architecture technique permettant l'intégration avec [nom du système tiers]."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
        
        - text: "Rédige une section dans un fichier Markdown expliquant comment la sécurité de l'architecture sera assurée, en tenant compte des aspects suivants : [détails de sécurité]."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
        
        - text: "Génère un fichier Markdown décrivant les modifications nécessaires de l'architecture en réponse aux retours des utilisateurs : [insérer ajustements]."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
        
        - text: "Crée un document en Markdown détaillant l'architecture du système, les choix technologiques, et les justifications associées."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
        
        - text: "Rédige un rapport en Markdown validant que les choix techniques sont optimaux en fonction des contraintes budgétaires et temporelles suivantes : [insérer détails]."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
        
        - text: "Crée un calendrier et un agenda en Markdown pour organiser une revue technique de l'architecture avec l'équipe, incluant les points à discuter."
          validationRequired: true
          validator: "Responsable Produit"
          collaboratesWith:
            - "Architecte Produit"
      observers:
        - "Architecte Produit"

    - name: "Architecte Produit"
      description: "Conçoit des plans pour construire des systèmes informatiques solides et adaptés aux besoins de l'entreprise."
      model: "llama3.2:1b"
      personaFile: "resources/architect-persona.md"
      sentences:
        - text: "Rédige la charte graphique du produit, en spécifiant les couleurs, typographies, éléments visuels et comportements interactifs à adopter pour l'interface utilisateur. Ce document doit être clair et adapté aux exigences de l'expérience utilisateur et aux contraintes techniques."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "UI/UX Designer"
        
        - text: "Rédige un document en Markdown spécifiant les exigences d'interface utilisateur pour le produit, en incluant les contraintes techniques, les comportements attendus et les éléments à intégrer dans le design. Ce document servira de base à la conception de l'interface."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "UI/UX Designer"
        
        - text: "Crée un diagramme d'architecture détaillant les composants front-end et back-end, ainsi que les interactions entre eux, en tenant compte des contraintes de performance et de scalabilité."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "Programmeur"
        
        - text: "Prépare un fichier de spécifications techniques en Markdown pour le front-end, en détaillant les choix technologiques (frameworks, langages) et les comportements d'interface, incluant également les interactions avec les API backend."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "Programmeur"
        
        - text: "Propose un plan détaillé pour l'intégration de l'interface avec les systèmes tiers via des API, en précisant les formats de données attendus et les protocoles utilisés. Ce plan doit être validé par les développeurs pour assurer une intégration fluide."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "Programmeur"
        
        - text: "Crée un fichier de configuration en YAML pour la gestion des utilisateurs, des sessions et des autorisations, en suivant les recommandations de sécurité et les besoins de scalabilité."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "Programmeur"
        
        - text: "Rédige un document Markdown expliquant comment l'interface doit être responsive et adaptable aux différentes tailles d'écran, tout en respectant les lignes directrices de l'architecture technique."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "UI/UX Designer"
        
        - text: "Prépare une documentation technique en Markdown pour le déploiement du front-end, en incluant les étapes d'installation, de configuration et les prérequis nécessaires à l'exécution du produit."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "UI/UX Designer"
            - "Programmeur"
        
        - text: "Implémente le code nécessaire pour les fonctionnalités de l'interface utilisateur, en suivant les spécifications définies dans la charte graphique et les exigences techniques. Assure-toi que le code respecte les normes de qualité et de sécurité."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "Programmeur"
        
        - text: "Développe et configure la logique métier côté front-end, en vous assurant que les données sont correctement récupérées et affichées dans l'interface utilisateur. Ce développement doit être conforme aux spécifications définies."
          validationRequired: true
          validator: "Architecte Produit"
          collaboratesWith:
            - "Programmeur"
      observers:
        - "UI/UX Designer"
        - "Programmeur"

    - name: "UI/UX Designer"
      description: "Crée des interfaces et des visuels qui rendent les applications et sites web agréables et faciles à utiliser."
      model: "llama3.2:1b"
      personaFile: "resources/designer-persona.md"
      sentences:
        - text: "Conçois les maquettes des interfaces utilisateurs pour la plateforme."
          validationRequired: false
          validator:
      collaboratesWith:
        - Programmeur

    - name: "Programmeur"
      description: "Écrit le code informatique qui permet aux logiciels de fonctionner correctement."
      model: "llama3.2:1b"
      personaFile: "resources/programmer-persona.md"
      sentences:
        - text: "Développe le code des fonctionnalités de la plateforme selon les spécifications et les maquettes."
          validationRequired: false
          validator:
      collaboratesWith:
        - QA
        - DevSecOps

    - name: "QA"
      description: "Teste les logiciels pour s'assurer qu'ils sont de bonne qualité et ne comportent pas de bugs."
      model: "llama3.2:1b"
      personaFile: "resources/qa-persona.md"
      sentences:
        - text: "Teste les fonctionnalités et identifie les bugs ou incohérences."
          validationRequired: false
          validator:
      collaboratesWith:
        - DevSecOps

    - name: "DevSecOps"
      description: "S'assure que les systèmes informatiques sont non seulement efficaces, mais aussi sécurisés contre les attaques."
      model: "llama3.2:1b"
      personaFile: "resources/devsecops-persona.md"
      sentences:
        - text: "Assure la sécurité du code et déploie l'infrastructure dans un environnement sécurisé."
          validationRequired: false
          validator:
      collaboratesWith:
        - Documentaliste

    - name: "Documentaliste"
      description: "Crée et organise des documents clairs pour expliquer les projets, les processus ou les produits d'une entreprise."
      model: "llama3.2:1b"
      personaFile: "resources/document-persona.md"
      sentences:
        - text: "Rédige la documentation finale sur les spécifications techniques et le fonctionnement du système."
          validationRequired: false
          validator:
      collaboratesWith:
        - Support Technique

    - name: "Support Technique"
      description: "Aide les utilisateurs en cas de problèmes avec les produits ou services, afin de garantir une bonne expérience."
      model: "llama3.2:1b"
      personaFile: "resources/support-persona.md"
      sentences:
        - text: "Fournis un guide de dépannage pour les utilisateurs en fonction de la documentation générée."
          validationRequired: false
          validator:
      collaboratesWith:
        - Product Marketing

    - name: "Product Marketing"
      description: "Présente et promeut des produits pour qu'ils trouvent leur public et rencontrent le succès commercial."
      model: "llama3.2:1b"
      personaFile: "resources/product-marketing-persona.md"
      sentences:
        - text: "Crée une campagne marketing pour le produit en utilisant les spécifications et les retours des utilisateurs."
          validationRequired: false
          validator:
      collaboratesWith:
        - Data Analyst

    - name: "Data Analyst"
      description: "Analyse les données pour en tirer des informations utiles qui aident l'entreprise à prendre de bonnes décisions."
      model: "llama3.2:1b"
      personaFile: "resources/data-analyst-persona.md"
      sentences:
        - text: "Analyse les résultats des campagnes marketing et les retours des utilisateurs pour ajuster la stratégie produit."
          validationRequired: false
          validator:
      collaboratesWith:
        - Product Owner
